name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name:  cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         
          sudo -H pip install virtualenv
          sudo -H pip install -r requirements.txt
          python train.py
          
          echo "MODEL METRICS"
          cat metrics.txt
